### ISSUE TITLE
npm install of electron-to-chromium does not install the latest 1.4.17 version

### ISSUE THREAD

**Issue by william-merussi-vv** [Kilian/electron-to-chromium#106]
npm view electron-to-chromium shows the latest version is 1.4.16  even though the latest version on https://www.npmjs.com/package/electron-to-chromium is 1.4.17

This is failing our npm install with:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for electron-to-chromium@^1.4.17
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'browserslist'
npm ERR! notarget
```

**Comment by Kilian** [comment]
Hi, you're probably using a mirror of NPM that hasn't updated yet. 

1.4.17 was released 16 hours ago and on NPM currently has 200K+ downloads so it's definitely available.

**Comment by william-merussi-vv** [comment]
Ye, sorry about that. Probably Nexus was outdated, it's fine now. Thank you
