### ISSUE TITLE
Cannot find module './full-chrome-versions' as of 1.3.0

### ISSUE THREAD

**Issue by pdhodgkinson** [Kilian/electron-to-chromium#11]
index.js references a file that does not exist. Broken in the last merge
`var fullChromeVersions = require('./full-chrome-versions');`
File _full-chrome-versions.js_ no longer exists... it should be _full-chromium-versions_

**Comment by jaridmargolin** [comment]
@pdhodgkinson even upon changing the resolution... there are references to both `fullChromeVersions` and `fullChromiumVersions`, in the code...

Are there any tests for test library? Issues like this should be caught prior to release.

**Comment by Kilian** [comment]
This is resolved in 1.3.1!

(and test are coming up)

**Comment by pdhodgkinson** [comment]
There actually appears to be still issues:
https://github.com/Kilian/electron-to-chromium/blame/master/index.js#L13
This still reference undefined variables (fullChromeVersions and chromeVersions)  that have changed

**Comment by Kilian** [comment]
You're right :( 1.3.2 coming up.

**Comment by Kilian** [comment]
1.3.2 is publish with the correct references.
