### ISSUE TITLE
npm install of electron-to-chromium does not install the latest 1.4.332 version

### ISSUE THREAD

**Issue by aj84276** [Kilian/electron-to-chromium#145]
1.4.332 is released? could not find on npm repo.

It was working fine until couple of hours

warning npm-check-updates > pacote > cacache > @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://www.npmjs.com/package/electron-to-chromium/-/electron-to-chromium-1.4.332.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in

**Comment by anshulgargamway** [comment]
We are also facing same issue.

**Comment by bpwolki** [comment]
Same here.
Edit: Looks like everyone has that issue judging by the download numbers on npmjs. 0 downloads for 1.4.331 but over 1.3 million for 1.4.330

**Comment by nagarro-tanuj** [comment]
We as well are blocked due to same issue

**Comment by VKolliSignet** [comment]
We are also facing the issue [24](
ERR! 404 Not Found - GET https:///electron-to-chromium/-/electron-to-chromium-1.4.332.tgz - 
Asset 'electron-to-chromium-1.4.332' not found for package with name: 'electron-to-chromium', & version: '1.4.332'[25]

**Comment by alvarofernandezavalos** [comment]
Same problem here !

**Comment by aj84276** [comment]
seems it started working now as the package is available to download from npm

**Comment by alvarofernandezavalos** [comment]
Yes, now it's working.
But in this page still version 1.4.331.
https://www.npmjs.com/package/electron-to-chromium?activeTab=readme
Anybody know how work this?

Now the version is 1.4.332 in npmjs.

**Comment by bpwolki** [comment]
Works now. Thanks.

**Comment by Kilian** [comment]
NPMjs had an incident unfortunately: https://status.npmjs.org/incidents/486c00gg9wt4 which has been solved since.

**Comment by alvarofernandezavalos** [comment]
> NPMjs had an incident unfortunately: https://status.npmjs.org/incidents/486c00gg9wt4 which has been solved since.

Thank you !
