### ISSUE TITLE
electron-to-chromium is not in this registry

### ISSUE THREAD

**Issue by adihanifsdr** [Kilian/electron-to-chromium#146]
Hello electron-to-chromium team,

I've encountered an issue while trying to install the electron-to-chromium package. When I attempt the installation, I receive an error message stating that the package is not found in the registry. Here is the error message I get:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET 
npm ERR! 404
npm ERR! 404  'electron-to-chromium@' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
I have already tried various troubleshooting steps, such as checking the package name and version, clearing the npm cache, and verifying my network connection and proxy settings. However, the issue persists.

I would greatly appreciate any assistance you can provide to resolve this issue. Please let me know if you require any additional information or if there is any workaround available.

Thank you in advance for your help.

**Comment by Kilian** [comment]
for future reference: we publish to NPM, https://www.npmjs.com/package/electron-to-chromium and have no explicit support for other registries.
