### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by char0n** [Kilian/electron-to-chromium#16]
Hello, is it possible to incorporate the LICENSE file inside the npm package and this github repo ? Now it's missing. The source code should be accompanied by full license text (in a form of a license file). If the license file is not in the npm package and the github repo a lot of people cannot use it.

Currently it's not apparent how your source code is even licensed. Can this be remedied so that we can use your library (which is great btw) without problems ?

Thank you

**Comment by Kilian** [comment]
Hi, you can find the license in the README and in the package.json. This is continuously monitored by https://app.fossa.io/projects/git%2Bgithub.com%2FKilian%2Felectron-to-chromium/refs/branch/master/301e644197703da9fd5b36d6bfcaad366d22dbb9/preview to verify the license is unchanged.

**Comment by Kilian** [comment]
See package.json: https://github.com/Kilian/electron-to-chromium/blob/master/package.json#L28

**Comment by char0n** [comment]
I know FOSSA and I know you have it in you package.json (just a name). When you run your lib through legal department of any company it will not stand. For example in my case I would need a full license text with copyright notice. Is it possible for you to create a `LICENSE` file inside your repo and npm package and with proper copyright notice ?

This is an example of how this can be done: https://github.com/char0n/ramda-adjunct/blob/master/LICENSE.md (the second line is called copyright notice)

I would very much like to use your code, but without this I cannot.

**Comment by Kilian** [comment]
I can add it to the repository. Do you need it to be available in the npm package too? I'd prefer to keep it out of there to keep the file size of it down.

**Comment by char0n** [comment]
This is the template of ISC: https://opensource.org/licenses/ISC

We have to fill the copyright notice, without it you really have no license for your code. The license specifically deals with the copyright notice that currently does not exist. I can help you by issuing a PR if you'll agree.

If not, I understand, and I'll be looking for alternative to your code.

Thank you

**Comment by char0n** [comment]
@Kilian yep, as npm package is a code distribution, without the LICENSE in npm package, I still cannot use it (well technically nobody can).

**Comment by Kilian** [comment]
okay, I'll add that shortly, and will be published with the next automatic release

**Comment by char0n** [comment]
Cool thank you very much.

**Comment by Kilian** [comment]
There we go, will be in the next npm release, 1.3.55 :)

**Comment by honzajavorek** [comment]
BTW newer npm versions automatically add `LICENSE` file to the distributions if its present and it's not possible to avoid it even by `.npmignore`. The distributed code is effectively unlicensed without the file (regardless what's indicated in the `package.json`), which basically means you keep full copyright and nobody can use such code.

Also, FWIW, some licenses even explicitly say you should bundle the license text with any "copy" of the software and ISC is no exception:

> hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

**Comment by char0n** [comment]
@Kilian thanks, any timeline on 1.3.53 ? I don't want to push it, but is it possible to go for a patch release ? ;]

**Comment by char0n** [comment]
1.3.54 already has a LICENSE. @Kilian thank you very much again. I'm closing this issue now.
