### ISSUE TITLE
Update for new Electron versions

### ISSUE THREAD

**Issue by Thomas101** [Kilian/electron-to-chromium#19]
Hey, first of all super handy repo, thanks 👍.

It looks like the last version that was released and published out to npm was `v1.3.113` at the beginning of feb, which only goes up to electron 4.0.4 and 5.0.0-beta.1. I can see that new version commits have been generated since then, but was just wondering if the update script was failing?

Thanks :)

**Comment by Kilian** [comment]
Sorry! It runs automated so I hadn't noticed yet. I triggered a new version and will see what happened with the previous updates

**Comment by Thomas101** [comment]
Awesome, thanks for the quick turnaround :)
