### ISSUE TITLE
Separate file with versions

### ISSUE THREAD

**Issue by ai** [Kilian/electron-to-chromium#2]
I am implementing `electron` support directly in Browserslist. And to reduce Browserslist file size, I need to separated `electron-to-chromium/versions` with just short versions.

/cc @Kilian

**Comment by Kilian** [comment]
Sure, no problem :) Would doing an import { versions } from 'electron-to-chromium'; also not be transpiled down to just versions, or does it keep the entire file around?

I'll have to figure out how so allow for that type of import. I'll also need to consider if keeping the electronToBrowserList(); function is then still useful to keep around. Any tips or thoughts?

**Comment by ai** [comment]
`import { versions } from 'electron-to-chromium'` is not a solution, because it will import whole `electron-to-chromium/index.js` to Browserslist on client side ;).

Just move `var versions = {` to `versions.js` and import it in `index.js`:

```js
var versions = require('./versions')
```

**Comment by Kilian** [comment]
just pushed to this branch:
https://github.com/Kilian/electron-to-chromium/tree/separate-version-file

Will merge it in tomorrow (so I can check if my automated update script works tonight). Anything you wanna add?

**Comment by ai** [comment]
@Kilian you are fast :) Looks great.

I finished integration (all `electron <= 10` queries will work too). Will release Browserslist and Autoprefixer just after your release.

Also what is your Twitter name?

**Comment by Kilian** [comment]
Thanks! Twitter name is @kilianvalkhof.

**Comment by ai** [comment]
Ping :). Browserslist and Autoprefixer releases are waiting ;)

**Comment by Kilian** [comment]
1.2.0 is ready for you! :)

**Comment by ai** [comment]
Thanks :)
