### ISSUE TITLE
npm install of electron-to-chromium does not install the latest 1.3.122 version.

### ISSUE THREAD

**Issue by vakeeel** [Kilian/electron-to-chromium#20]
`npm view electron-to-chromium` shows the latest version is 1.3.121 even though the latest version on https://www.npmjs.com/package/electron-to-chromium is 1.3.122.

This is failing our `npm install` with:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for electron-to-chromium@^1.3.122
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'browserslist'
npm ERR! notarget

**Comment by Kilian** [comment]
Just tried it and installing succeeds, so I think you got it the moments between it being released (which happened ~12 hours ago) and it being available? If you try again it should work :)

**Comment by ayusshar** [comment]
Getting Same error.
Is v1.3.122 is not released?

npm ERR! code ETARGET
npm ERR! notarget No matching version found for electron-to-chromium@^1.3.122
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'browserslist'
npm ERR! notarget 

And when i run, 
**npm install electron-to-chromium --save**

It is installing + electron-to-chromium@1.3.121

**Comment by Kilian** [comment]
This is what I get. I'll escalate this to NPM.
```
[kilian:~/workspace/personal/e2ctest]$ npm install electron-to-chromium@1.3.122
+ electron-to-chromium@1.3.122
added 1 package from 1 contributor and audited 1 package in 0.631s
found 0 vulnerabilities
```

**Comment by ayusshar** [comment]
> This is what I get. I'll escalate this to NPM.
> 
> ```
> [kilian:~/workspace/personal/e2ctest]$ npm install electron-to-chromium@1.3.122
> + electron-to-chromium@1.3.122
> added 1 package from 1 contributor and audited 1 package in 0.631s
> found 0 vulnerabilities
> ```

I guess if we do **npm i electron-to-chromium**, it should install the latest version and that is **1.3.122** but it is installing **1.3.121**. Can you please try that once, without mentioning the version

**Comment by Kilian** [comment]
I tried `npm install electron-to-chromium`, `npm install electron-to-chromium@1.3.122` and `npm install electron-to-chromium@^1.3.122`, they all give me 1.3.122.

**Comment by ayusshar** [comment]
**npm install electron-to-chromium**

Above command is always giving 1.3.121

npm i electron-to-chromium
npm notice created a lockfile as package-lock.json. You should commit this file.

+ electron-to-chromium@1.3.121
added 1 package from 1 contributor and audited 1 package in 1.498s
found 0 vulnerabilities

**Comment by antetmc2** [comment]
Not working for me as well when installing `browserslist`

**Comment by vakeeel** [comment]
Working for me this morning 👍

**Comment by mdblr** [comment]
Seeing this issue currently, albeit intermittently.

`npm ERR! notarget No matching version found for electron-to-chromium@^1.3.122`

**Comment by Kilian** [comment]
My money is on some CDN issue. NPM cleared the package cache so lets hope that resolves it for everyone. Please let me know!

**Comment by ayusshar** [comment]
Yes @Kilian it is resolved now. Cheers
Thanks for prompt response.
