### ISSUE TITLE
browserslist not taking electron 5.0.2

### ISSUE THREAD

**Issue by Noitidart** [Kilian/electron-to-chromium#22]
Using latest:

```
PS C:\Users\Mercurius\Documents\GitHub\rxjse> npm list electron-to-chromium
yanky-panky@1.0.0 C:\Users\Mercurius\Documents\GitHub\rxjse
`-- @babel/preset-env@7.4.5
  `-- browserslist@4.6.0
    `-- electron-to-chromium@1.3.137
```

I had to put `5.0` for it to work. Opening issue per - https://github.com/browserslist/browserslist/issues/351#issuecomment-495633908

**Comment by Kilian** [comment]
See my reply here: https://github.com/browserslist/browserslist/issues/351#issuecomment-495868709 Browserlist only uses version.js and not full-versions.js, so only supports versions in the form of "5.0".
