### ISSUE TITLE
Error to install electron-to-chromium

### ISSUE THREAD

**Issue by carojaspaz** [Kilian/electron-to-chromium#28]
C:\WINDOWS\system32>npm i electron-to-chromium
npm ERR! Unexpected end of JSON input while parsing near '....188":{"name":"electr'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2019-11-08T04_37_52_512Z-debug.log

**Comment by Kilian** [comment]
Works fine for me. Are you using another source than npmjs.com?

**Comment by Kilian** [comment]
A cache clear could help: https://github.com/Kilian/electron-to-chromium/issues/27

**Comment by brettz9** [comment]
Am based in China with poor connectivity issues. Same issue causing me to be unable to install several packages. `npm get registry` does show "https://registry.npmjs.org/". Did not work with a temporary cache... But using `npm cache clean --force` did work (in my case at least). Thanks!

**Comment by brettz9** [comment]
Out of curiosity, any idea why your package has been reported with this in particular?

**Comment by matiasperrone** [comment]
This link has the error https://registry.npmjs.org/electron-to-chromium
`"keywords":["electron","chrome","browserlist"],"author":{{"_id":"electron-to-chromium`
Check the double "{"

**Comment by Kilian** [comment]
So, I don't see any error on that URL and a quick search for `{{` yields nothing as well. That file is also generated by (some version of) npmjs.org so it's also not something I can influence. 

@matiasperrone are you using a mirror and if so, which one?

**Comment by matiasperrone** [comment]
Now it's fixed!... a npm typo?

**Comment by matiasperrone** [comment]
@Kilian close this issue, because seems corrected 🤔
