### ISSUE TITLE
Add note, that it is used in Browserslist

### ISSUE THREAD

**Issue by ai** [Kilian/electron-to-chromium#3]
[Some users](https://twitter.com/lynchy010/status/834865665869746181) thinks that you need combine this library with Autoprefixer and miss that it already used.

So we could add some note:

```
This package is used in [Browserslist], so you can use `electron >= 1.4` in Autoprefixer, Stylelint, babel-present-env and eslint-plugin-compat
```

Also it will show how awesome your project is :).

**Comment by Kilian** [comment]
You convinced me ;)

**Comment by Kilian** [comment]
Additionally, I will deprecate the electronToBrowserList API for clarity.

**Comment by Kilian** [comment]
Added links and deprecation notice!
