### ISSUE TITLE
Electron 9 is reported as Chromium 82, when it is actually 83

### ISSUE THREAD

**Issue by lights0123** [Kilian/electron-to-chromium#31]
Placing `electron 9` in a .browserslistrc (and hence this project) returns that it maps to Chromium 82. However, Chromium 82 was skipped and never released, and Electron [uses Chromium 83](https://www.electronjs.org/blog/electron-9-0). This causes problems with many browser preset things, as it compiles for a browser that never was released.

**Comment by Kilian** [comment]
Thanks, releasing a fix now. The 9 branch had chromium 82 at some point, but that version got skipped. The value got overridden so changed that to work better.
