### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by HonkingGoose** [Kilian/electron-to-chromium#39]
I thought this repository had no continuous integration (you do, but it's Travis CI...), so I went to work and made a full GitHub action workflow. So if you want to migrate to GitHub actions, I've got it ready for you...

The benefits would be:

- The configuration lives in the repository.
- You don't have to leave the GitHub webpage to manage your tests, or to view the results.
- Tests run on on each push to `master` and on each pull request to `master`.

Drawbacks:

- I have not found a way to run the Code coverage report after the GitHub actions completes.

Let me know if this is even a thing you might want?

**Comment by Kilian** [comment]
Hey HonkingGoose. Right now this script runs every 15 minutes: https://github.com/Kilian/electron-to-chromium/blob/master/automated-update.js 

This checks if Electron has updated. If it has, it rebuilds this package, runs the tests and then makes a new release and pushed a new tag and the latest master. After that Travis CI and Codecov run, but the tests happens before a release and the entire process is automated.

I like that this checks pull requests too but I'm not sure what, other than that, it can replace in the workflow above.

**Comment by HonkingGoose** [comment]
Thanks for responding!

I think you can also use GitHub actions to run on a `cron` job, but I would have to look into the docs to check. I also think it's possible to make releases with GitHub Actions as well.

I can make a GitHub Action just to cover pull requests to the default branch.
That way you have that part of the workflow covered with tests also.

Do you want me to create a pull request with Node.js GitHub actions for pull requests?

**Comment by Kilian** [comment]
> Do you want me to create a pull request with Node.js GitHub actions for pull requests?

Yeah, that's be cool!

**Comment by HonkingGoose** [comment]
Cool! I'll make a pull request for you later today.
