### ISSUE TITLE
transform-class-properties still required for Electron 1.6.1

### ISSUE THREAD

**Issue by TimNZ** [Kilian/electron-to-chromium#5]
I don't know what Repo to post this issue in, if it is an issue or a Beginner thing as I'm just guessing at a lot of Babel stuff.

Using electron-forge, with electron-compile, targeting Electron 1.6.1
Using preset 'env', still need to explicitly include plugin "transform-class-properties"

**Comment by Kilian** [comment]
Hi @TimNZ, It's kind of the wrong repository but I asked the electron-forge people: it's a limitation of a third party tool (react-proxy) and not that Chromium is actually missing features. Electron-forge will be updated to use the class transform by default to help with these issues so it works as expected. 

For now, you do need to explicitly add the plugin and then it will work.

**Comment by TimNZ** [comment]
Thanks @Kilian appreciate the follow up.
One migration issue down, about 20 more to go :)
