### ISSUE TITLE
Check files published to npm

### ISSUE THREAD

**Issue by hzoo** [Kilian/electron-to-chromium#7]
Was looking at https://unpkg.com/electron-to-chromium@1.2.8/ and I was wondering whether all those files need to be published or not.

It looks like only main/versions/full-versions are necessary? can use package.json files or npmignore  https://docs.npmjs.com/files/package.json#files

**Comment by Kilian** [comment]
Didn't know that existed. Yeah I think the following files can go in a .npmignore:

* automated-update.js
* build.js

This does mean people won't be able to use the npm module to build it themselves, but I suppose that's fine as the git repository takes care of that. Is that a fair estimation @hzoo?

**Comment by Kilian** [comment]
Actually, I just need to add 
```json
  "files": [
    "versions.js",
    "full-versions.js"
  ],
```
to my package.json, since index.js, being main, is already included. Everything else will be ignored.

**Comment by Kilian** [comment]
There we go. README.md, CHANGELOG.md will still be included but I think the other files wont, whenever the next version is released.

**Comment by hzoo** [comment]
Cool sounds good! can watch https://unpkg.com/electron-to-chromium in the next release

can also do https://docs.npmjs.com/cli/pack to test locally I believe

**Comment by Kilian** [comment]
`npm pack` does the trick, looks great. Next automated release will have the smaller footprint!
