### ISSUE TITLE
Missing module './full-chrome-versions'

### ISSUE THREAD

**Issue by GabeMedrash** [Kilian/electron-to-chromium#9]
Hi @Kilian,

Bootstrapping a new project with `babel-preset-env` (which by default uses `electron-to-chromium`) and hitting the following error:
```
Error: Cannot find module './full-chrome-versions' (While processing preset: ".../node_modules/babel-preset-env/lib/index.js")
```
It [looks like](https://github.com/Kilian/electron-to-chromium/blob/master/package.json#L6) this repo isn't distributing the file `full-chrome-versions.js`. 

Simple fix? Bigger change? Happy to submit a PR if you need a hand.

**Comment by Kilian** [comment]
yeah, about 4 minutes ago I releases v1.3.0, which had that bug. But about 10 seconds ago, I released v1.3.1, that fixes it! (you're _fast_)

**Comment by sergiotapia** [comment]
Just faced this bug to, how I force grab the new version just run `yarn`?

**Comment by sergiotapia** [comment]
Related https://github.com/rails/webpacker/issues/200

**Comment by GabeMedrash** [comment]
Ha, thanks for the quick fix!
