### ISSUE TITLE
Provide JSON-format files

### ISSUE THREAD

**Issue by g-plane** [Kilian/electron-to-chromium#99]
Currently this library only provide JavaScript files which is generated `JSON.stringify`, but it's inconvenient for using those data in non-Node.js projects even in non-JavaScript projects.

I think it would be better to provide JSON files besides the current JavaScript files.

For additional context: I'm working on a [Rust-based Browserslist](https://github.com/g-plane/browserslist-rs), and so far the only way to read those data is to strip the starting `module.exports = ` and the ending `;` then parse the rest string as JSON. If this library can provide JSON files directly, reading those data can be easy.

Thanks!

**Comment by Kilian** [comment]
hey, sure!

**Comment by g-plane** [comment]
Can I open a PR for this?

**Comment by Kilian** [comment]
Gimme 10 minutes and I'll have it in, Or do you have specific needs for the JSON?

**Comment by g-plane** [comment]
No, just same structures. Minification could be better but optional.

**Comment by Kilian** [comment]
I haven't done minification for the JS files since that can happen in a later step and it makes the files easily scannable for manual lookups, but I think the JSON should be fine being minified. PR incoming!

**Comment by g-plane** [comment]
Yes, I mean JSON should be minified, not JS files.

**Comment by Kilian** [comment]
@g-plane Let me know if #100 works for you!

**Comment by Kilian** [comment]
Just published this as 1.4.0
